# Generated by Django 2.2.6 on 2019-12-01 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0002_auto_20191201_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expaire_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reg_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
