# Generated by Django 2.2.6 on 2019-12-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0003_auto_20191201_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expaire_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reg_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
