# Generated by Django 2.2.6 on 2019-12-01 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0004_auto_20191201_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(default=datetime.date.today)),
                ('pay_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('due', models.FloatField()),
                ('note', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifi.Customer')),
                ('staf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifi.UserMain')),
            ],
        ),
    ]
